services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - NODE_FUNCTION_ALLOW_EXTERNAL=string-similarity
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: